### ISSUE TITLE
Build on top of React

### ISSUE THREAD

**Issue by igorw** [bergie/dnode-php#10]
I created a library for building a socket server: https://github.com/react-php/react

It has a WIP event loop component that could be used by the client as well.

The main benefit of having dnode on top of SocketServer is that every library using the SocketServer EventLoop can be run in the same loop easily. The other thing is that I want to create additional EventLoop implementations (eg. libevent), so that we can get performance gains but still have a stream_select fallback.

I'm very interested in any feedback from other projects trying to integrate the library, so an outside view would be interesting for me.

**Comment by igorw** [comment]
Note: the stream_socket_client should in that case use the STREAM_CLIENT_ASYNC_CONNECT flag.

**Comment by bergie** [comment]
That sounds like a good fit for DNode. Not sure when I have time to integrate, though
