### ISSUE TITLE
Getting an Operation timed out

### ISSUE THREAD

**Issue by chrismark** [bergie/dnode-php#16]
Hi,

I'm using php 5.3 and dnode-php 0.0.2 from https://packagist.org/packages/dnode/dnode.

Tested running examples/simple/server.php and after a while it stops and display this:

PHP Warning:  stream_socket_accept(): accept failed: Operation timed out in in /path/packages/vendor/dnode/dnode/src/DNode/DNode.php on line 55

In that line is

```
while ($stream = stream_socket_accept($server)) {
       $this->handleConnection($stream, $params);
}
```

I looked into http://php.net/manual/en/function.stream-socket-accept.php and it accepts timeout as second arg and it uses as default what's in ini_get("default_socket_timeout") which is 60 in mine so it stops after 60 seconds. Setting it to -1 seems to work and it waits forever.

**Comment by igorw** [comment]
If you use `dev-master` you should not have that problem anymore.

**Comment by igorw** [comment]
@bergie can you maybe tag another release?

**Comment by bergie** [comment]
@igorw done: https://github.com/bergie/dnode-php/tags

**Comment by igorw** [comment]
Thanks, however that's still missing the two PRs you merged via web. Sorry for nagging :)

**Comment by bergie** [comment]
@igorw oops, fixed. There is a 0.1.1 now.

**Comment by igorw** [comment]
Thanks Henri!
