### ISSUE TITLE
Dnode-php server process' memory usage climbs every time client contacts it

### ISSUE THREAD

**Issue by chrismark** [bergie/dnode-php#21]
Hi.

I'm using dnode-php 0.1.2 and php 5.3

I'm testing the example code under example/simple. I noticed that the dnode-php server process' memory usage climbs up everytime dnode-php client connects to it. Every connect of client, dnode-php server memory usage climbs a few KBs (>10KB) and does not appear to go back down when client ends its connection.

**Comment by chrismark** [comment]
Not sure if this is helpful but I've made these logs by adding calls to memory_get_usage() in parts of DNode.php, Session.php, Protocol.php, Stream.php

server - http://pastebin.com/9WCFmb7H

client - http://pastebin.com/jqFuYcNR

**Comment by igorw** [comment]
Confirmed, something is not being freed correctly. I'm looking into it.

Thanks for the report!

**Comment by igorw** [comment]
I've pushed a fix, can you verify?

**Comment by chrismark** [comment]
Hi igorw. Thanks for the library and looking into this. 

I tried your fix and memory appears to still go up if you wait a bit longer. Tested using code from your fork's example/test directory and had client delay changed to 20 seconds (that's how often we are gonna have it contact server but using dnode js) . 

I'm also viewing memory usage using top -pid <pid> and server starts at around 8MB then climbs up from there (right now it's at 11MB).

**Comment by igorw** [comment]
What PHP version are you using? How many concurrent dnode clients do you have?

In my tests with PHP 5.4.11-dev I had a single client connected and the server had a constant memory usage of 5120 KiB for 141717 requests. Then I started adding more concurrent clients, with 5 clients the server's memory usage increased to 5888 KiB.

**Comment by chrismark** [comment]
Hi igorw. We're using PHP 5.3.15 in our dev and 5.3.6 in prod. Doing the testing in dev. Testing only involves 1 server and 1 client process.

I've made another much longer testing (still with 20 second delay on client) and memory consumption appears to stop at 7424 KiB (had been that way for 9hours) for 2126 requests. Viewing memory consumption from the _top_ command says server process is at 15MB (it was at 14MB for a long time).

I'm gonna leave the processes running and report back to you tomorrow (it's 9pm now at my place).

**Comment by igorw** [comment]
Ok, sounds like the major memory problem has been fixed. There may be some minor one hiding somewhere though (as I noticed when connecting many concurrent clients).

**Comment by chrismark** [comment]
Checked today (around 7am) before our dev server went down (power outage) and it was at 15MB for 10hours since last check. From the logs, server process went to 7680 KiB for 3853 requests.

Agreed major problem is fixed and something minor is still there.

**Comment by igorw** [comment]
Alright, I will close this ticket then, and create a new one for the lower-prio issue. Thanks!
