### ISSUE TITLE
Start client in handleConnection()

### ISSUE THREAD

**Issue by bvoronov** [bergie/dnode-php#9]
Maybe I did something wrong, but examples from the package did not work until I put this code 

<pre>
// DNode/DNode.php
...
#113     if (!$started) {
#114         $client->start();
#115         $started = true;
#116     }
...
</pre>

to begin of the while 

<pre>
...
#77 while ($connected) {
#78     $readables = array($stream);
#79     $priority = null;

        if (!$started) {
            $client->start();
            $started = true;
        }
 ...
</pre>

_sorry for my english_

**Comment by bergie** [comment]
Thanks!
